### ISSUE TITLE
Viewing a past order

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#29]
Background: An existing user that has one previous order
     As an authenticated user
     When I visit "/orders"
     Then I should see my past order
     And I should see a link to view that order
     And when I click that link
     Then I should see each item that was order with the quantity and line-item subtotals
     And I should see links to each item's show page
     And I should see the current status of the order **(ordered, paid, cancelled, completed)**
     And I should see the total price for the order
     And I should see the date/time that the order was submitted
     If the order was completed or cancelled
     Then I should see a timestamp when the action took place

**Comment by JStans12** [comment]
I should see links to each items show page. <-- I think thats all we need.

**Comment by rtravitz** [comment]
Great catch and change @JStans12.

Still need to add:

An assertion in the feature test that the datetime shows up.

An assertion that each individual item in the order links to its show page

A way to lockdown the page so that users can't visit something like /orders/1 if the order does not belong to them.

A sad path test for what happens when a user who doesn't own the order tries to visit its  page.

**Comment by rtravitz** [comment]
I'll take this one
