### ISSUE TITLE
Adding items to the cart

### ISSUE THREAD

**Issue by bfpepper** [bfpepper/little-shop-1608#4]
Background: Items, and a user that is not logged in
     As a visitor
     When I visit any page with an item on it
     I should see a link or button for "Add to Cart"
     When I click "Add to cart" for that item
     And I click a link or button to view cart
     And my current path should be "/cart"
     And I should see a small image, title, description and price for the item I just added
     And there should be a "total" price for the cart that should be the sum of all items in the cart

**Comment by rtravitz** [comment]
Add model spec for cart! Need to test each method.

Current path is still /cart? after click on the cart button instead of /cart
Cart needs to display description for each item

Subtotal in cart at the bottom should be "Total". Actual subtotal should appear on the same line as a particular trip.

Update cart feature tests to reflect the addition of description and total

**Comment by JStans12** [comment]
@antciccone I know you did the model spec stuff. are you doing the rest of this card?

**Comment by antciccone** [comment]
@JStans12 yep i'll start doing the rest now
